/*
 * Copyright (C) 2012-2014 Arctium Emulation <http://arctium.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace WorldServer.Constants.Net
{
    // Value '0x2000' means not updated/implemented
    enum ClientMessage : ushort
    {
        #region Account
        #endregion

        #region ChatEntity
        JoinChannel                          = 0x2000,
        LeaveChannel                         = 0x2000,
        ReportIgnored                        = 0x2000,
        ReportFiltered                       = 0x2000,
        RegisterAddonPrefixes                = 0x2000,
        UnregisterAllAddonPrefixes           = 0x2000,
        MessageChannel                       = 0x2000,
        AddonMessageChannel                  = 0x2000,
        MessageWhisper                       = 0x2000,
        AddonMessageWhisper                  = 0x2000,
        MessageGuild                         = 0x2000,
        AddonMessageGuild                    = 0x2000,
        MessageOfficer                       = 0x2000,
        AddonMessageOfficer                  = 0x2000,
        MessageAfk                           = 0x2000,
        MessageDnd                           = 0x2000,
        ChannelList                          = 0x2000,
        ChannelDisplayList                   = 0x2000,
        ChannelPassword                      = 0x2000,
        ChannelSetOwner                      = 0x2000,
        ChannelOwner                         = 0x2000,
        ChannelModerate                      = 0x2000,
        ChannelModerator                     = 0x2000,
        ChannelUnmoderator                   = 0x2000,
        ChannelMute                          = 0x2000,
        ChannelUnmute                        = 0x2000,
        ChannelInvite                        = 0x2000,
        ChannelKick                          = 0x2000,
        ChannelBan                           = 0x2000,
        ChannelUnban                         = 0x2000,
        ChannelAnnouncements                 = 0x2000,
        ChannelSilenceVoice                  = 0x2000,
        ChannelUnsilenceVoice                = 0x2000,
        ChannelSilenceAll                    = 0x2000,
        ChannelUnsilenceAll                  = 0x2000,
        ChannelVoiceOn                       = 0x2000,
        ChannelVoiceOff                      = 0x2000,
        ChannelDeclineInvite                 = 0x2000,
        MessageSay                           = 0x2000,
        MessageEmote                         = 0x2000,
        MessageYell                          = 0x2000,
        MessageParty                         = 0x2000,
        AddonMessageParty                    = 0x2000,
        MessageRaid                          = 0x2000,
        AddonMessageRaid                     = 0x2000,
        MessageInstanceChat                  = 0x2000,
        AddonMessageInstanceChat             = 0x2000,
        MessageRaidWarning                   = 0x2000,
        #endregion

        #region Global
        GuildRequestGuildXP                  = 0x2000,
        GuildPromoteMember                   = 0x2000,
        GuildDemoteMember                    = 0x2000,
        GuildAssignMemberRank                = 0x2000,
        GuildDeclineInvitation               = 0x2000,
        GuildAutoDeclineInvitation           = 0x2000,
        GuildLeave                           = 0x2000,
        GuildOfficerRemoveMember             = 0x2000,
        GuildAddRank                         = 0x2000,
        GuildDeleteRank                      = 0x2000,
        GuildShiftRank                       = 0x2000,
        GuildSetRankPermissions              = 0x2000,
        GuildDelete                          = 0x2000,
        GuildQueryMemberRecipes              = 0x2000,
        GuildQueryRecipes                    = 0x2000,
        GuildQueryMembersForRecipe           = 0x2000,
        GuildQueryNews                       = 0x2000,
        GuildGetRanks                        = 0x2000,
        GuildNewsUpdateSticky                = 0x2000,
        GuildSetAchievementTracking          = 0x2000,
        GuildSetFocusedAchievement           = 0x2000,
        GuildGetAchievementMembers           = 0x2000,
        GuildSetMemberNote                   = 0x2000,
        GuildGetRoster                       = 0x2000,
        GuildUpdateMotdText                  = 0x2000,
        GuildUpdateInfoText                  = 0x2000,
        LFGuildGetGuildPost                  = 0x2000,
        LFGuildGetRecruits                   = 0x2000,
        LFGuildDeclineRecruit                = 0x2000,
        LFGuildGetApplications               = 0x2000,
        LFGuildRemoveRecruit                 = 0x2000,
        GuildChallengeUpdateRequest          = 0x2000,
        GuildChangeNameRequest               = 0x2000,
        GuildBankLogQuery                    = 0x2000,
        GuildBankRemainingWithdrawMoneyQuery = 0x2000,
        GuildPermissionsQuery                = 0x2000,
        GuildEventLogQuery                   = 0x2000,
        GuildBankSetTabText                  = 0x2000,
        GuildBankTextQuery                   = 0x2000,
        GuildReplaceGuildMaster              = 0x2000,
        GuildMemberSendSoRRequest            = 0x2000,
        GuildAddBattlenetFriend              = 0x2000,
        ChallengeModeRequestMapStats         = 0x2000,
        ChallengeModeRequestLeaders          = 0x2000,
        GetChallengeModeRewards              = 0x2000,
        #endregion

        #region UserClient
        SetRole                              = 0x2000,
        InitiateRolePoll                     = 0x2000,
        BFMgrEntryInviteResponse             = 0x2000,
        BFMgrQueueInviteResponse             = 0x2000,
        BFMgrQueueExitRequest                = 0x2000,
        RequestBattlefieldStatus             = 0x2000,
        StartWarGame                         = 0x2000,
        StartSpectatorWarGame                = 0x2000,
        AcceptWargameInvite                  = 0x2000,
        WorldTeleport                        = 0x2000,
        RequestRatedBattlefieldInfo          = 0x2000,
        DBQueryBulk                          = 0x2000,
        PlayerLogin                          = 0x2000,
        WardenData                           = 0x2000,
        GetPVPOptionsEnabled                 = 0x2000,
        CommentatorStartWargame              = 0x2000,
        CommentatorEnable                    = 0x2000,
        CommentatorGetMapInfo                = 0x2000,
        CommentatorGetPlayerInfo             = 0x2000,
        CommentatorEnterInstance             = 0x2000,
        CommentatorExitInstance              = 0x2000,
        RequestPartyJoinUpdates              = 0x2000,
        WorldPortResponse                    = 0x2000,
        SendMail                             = 0x2000,
        AcceptGuildInvite                    = 0x2000,
        PartyInvite                          = 0x2000,
        PartyInviteResponse                  = 0x2000,
        GuildInviteByName                    = 0x2000,
        DFProposalResponse                   = 0x2000,
        DFJoin                               = 0x2000,
        LFGListJoin                          = 0x2000,
        LFGListUpdateRequest                 = 0x2000,
        LFGListLeave                         = 0x2000,
        LFGListGetStatus                     = 0x2000,
        DFLeave                              = 0x2000,
        DFSearchJoin                         = 0x2000,
        DFSearchLeave                        = 0x2000,
        DFGetSystemInfo                      = 0x2000,
        DFGetJoinStatus                      = 0x2000,
        DFSetComment                         = 0x2000,
        DFSetRoles                           = 0x2000,
        DFBootPlayerVote                     = 0x2000,
        DFTeleport                           = 0x2000,
        SetEveryoneIsAssistant               = 0x2000,
        LFGuildAddRecruit                    = 0x2000,
        LFGuildSetGuildPost                  = 0x2000,
        LFGuildBrowse                        = 0x2000,
        SendSoRRequestViaAddress             = 0x2000,
        SendSoRRequestViaBnetAccountID       = 0x2000,
        BattlePetRequestJournalLock          = 0x2000,
        BattlePetRequestJournal              = 0x2000,
        BattlePetDeletePet                   = 0x2000,
        BattlePetDeletePetCheat              = 0x2000,
        BattlePetModifyName                  = 0x2000,
        BattlePetSummon                      = 0x2000,
        BattlePetSetBattleSlot               = 0x2000,
        BattlePetSetFlags                    = 0x2000,
        MountSetFavorite                     = 0x2000,
        DoReadyCheck                         = 0x2000,
        ReadyCheckResponse                   = 0x2000,
        SetActionButton                      = 0x2000,
        PetBattleInput                       = 0x2000,
        PetBattleReplaceFrontPet             = 0x2000,
        SupportTicketSubmitComplaint         = 0x2000,
        SupportTicketSubmitBug               = 0x2000,
        SupportTicketSubmitSuggestion        = 0x2000,
        PartyUninvite                        = 0x2000,
        SetLootMethod                        = 0x2000,
        LeaveGroup                           = 0x2000,
        SetPartyLeader                       = 0x2000,
        MinimapPing                          = 0x2000,
        ChangeSubGroup                       = 0x2000,
        SwapSubGroups                        = 0x2000,
        ConvertRaid                          = 0x2000,
        SetAssistantLeader                   = 0x2000,
        UpdateRaidTarget                     = 0x2000,
        SetPartyAssignment                   = 0x2000,
        SilencePartyTalker                   = 0x2000,
        RequestPartyMemberStats              = 0x2000,
        RandomRoll                           = 0x2000,
        SetActiveVoiceChannel                = 0x2000,
        VoiceAddIgnore                       = 0x2000,
        VoiceDelIgnore                       = 0x2000,
        MailReturnToSender                   = 0x2000,
        QueryScenarioPOI                     = 0x2000,
        ToggleDifficulty                     = 0x2000,
        AddBattlenetFriend                   = 0x2000,
        QueryCorpseLocationFromClient        = 0x2000,
        QueryCorpseTransport                 = 0x2000,
        CanDuel                              = 0x2000,
        TeleportToUnit                       = 0x2000,
        UpdateClientSettings                 = 0x2000,
        ResetInstances                       = 0x2000,
        SummonResponse                       = 0x2000,
        Complaint                            = 0x2000,
        CalendarGet                          = 0x2000,
        CalendarGetEvent                     = 0x2000,
        CalendarGuildFilter                  = 0x2000,
        CalendarEventInvite                  = 0x2000,
        CalendarRemoveInvite                 = 0x2000,
        CalendarEventRSVP                    = 0x2000,
        CalendarEventStatus                  = 0x2000,
        CalendarEventModeratorStatus         = 0x2000,
        CalendarRemoveEvent                  = 0x2000,
        CalendarCopyEvent                    = 0x2000,
        CalendarComplain                     = 0x2000,
        CalendarGetNumPending                = 0x2000,
        CalendarEventSignUp                  = 0x2000,
        CalendarAddEvent                     = 0x2000,
        CalendarUpdateEvent                  = 0x2000,
        KeepAlive                            = 0x2000,
        WhoIs                                = 0x2000,
        Who                                  = 0x2000,
        SetDungeonDifficulty                 = 0x2000,
        GMSurveySubmit                       = 0x2000,
        VoiceSessionEnable                   = 0x2000,
        ResurrectResponse                    = 0x2000,
        PetRename                            = 0x2000,
        BugReport                            = 0x2000,
        SetSavedInstanceExtend               = 0x2000,
        SetPlayerDeclinedNames               = 0x2000,
        QueryPlayerName                      = 0x2000,
        QueryRealmName                       = 0x2000,
        QueryGuildInfo                       = 0x2000,
        GMTicketCreate                       = 0x2000,
        GMTicketUpdateText                   = 0x2000,
        GMTicketGetTicket                    = 0x2000,
        GMTicketDeleteTicket                 = 0x2000,
        GMTicketResponseResolve              = 0x2000,
        GMTicketGetSystemStatus              = 0x2000,
        GMTicketGetCaseStatus                = 0x2000,
        GMTicketAcknowledgeSurvey            = 0x2000,
        GMLagReport                          = 0x2000,
        RequestAccountData                   = 0x2000,
        UpdateAccountData                    = 0x2000,
        UITimeRequest                        = 0x2000,
        LowLevelRaid                         = 0x2000,
        InspectPVP                           = 0x2000,
        OfferPetition                        = 0x2000,
        QuestPOIQuery                        = 0x2000,
        DanceStudioAddMove                   = 0x2000,
        BattlePayGetProductList              = 0x2000,
        BattlePayGetPurchaseList             = 0x2000,
        ShowTradeSkill                       = 0x2000,
        BattlePayDistributionAssignToTarget  = 0x2000,
        GuildSetGuildMaster                  = 0x2000,
        PetitionRenameGuild                  = 0x2000,
        RequestRaidInfo                      = 0x2000,
        BattlePayStartPurchase               = 0x2000,
        BattlePayConfirmPurchaseResponse     = 0x2000,
        BattlePayAckFailedResponse           = 0x2000,
        CheckRAFEmailEnabled                 = 0x2000,
        RecruitAFriend                       = 0x2000,
        SendContactList                      = 0x2000,
        AddFriend                            = 0x2000,
        DelFriend                            = 0x2000,
        SetContactNotes                      = 0x2000,
        BattlenetChallengeResponse           = 0x2000,
        AddIgnore                            = 0x2000,
        DelIgnore                            = 0x2000,
        SetRaidDifficulty                    = 0x2000,
        #endregion
    }
}
